---
title: "Maria Data SQ export "
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_pkg}
# install packages if not already installed and load them ----
if (!require("pacman")) install.packages("pacman")
pacman::p_load("tidyverse", 
               "jsonlite",
               "janitor",
               "httr",
               "readr",
               "glue")
```

## Setup

```{r setup_base, echo=FALSE}
# set API token --------
api_token <- as.character(read_tsv("private/lizzie_SQ_api_token.txt", col_names = FALSE)) 

# Set base URL for all SQ+ api queries ----
base_url <- "https://squidle.org/api/" 
  
# basic request function (for non-polling endpoints)=======================
get_func <- function(url){
    
    out1 <-
      GET(url,add_headers("X-Auth-Token"= api_token), content_type_json()) %>% 
      content("text", encoding = "UTF-8") %>% 
      fromJSON(flatten = TRUE) 
    
    return(out1)
    
}

# Function: Run json call for polling requests============================
run_json_call <- function(full_url, api_token) {
  # Hit the API to get data
  res <- GET(URLencode(full_url), add_headers("X-auth-token" = api_token), content_type_json())
  json <- jsonlite::fromJSON(content(res, 'text', encoding = "UTF-8"), simplifyVector = TRUE, flatten = TRUE)

  # Poll request
  host <- "https://squidle.org"
  res2 <- NULL
  
  # Initialize progress bar
  #pb <- txtProgressBar(min = 0, max = 100, style = 3)
  
  while (TRUE) {
    # Poll the status URL to check progress
    res_raw <- GET(URLencode(paste0(host, json$status_url)), add_headers("X-auth-token" = api_token), content_type_json())
    res1 <- jsonlite::fromJSON(content(res_raw, 'text', encoding = "UTF-8"), simplifyVector = TRUE, flatten = TRUE)
    
    # Check if server indicates result is available
    if (res1$result_available || res1$status == "done") {
      res2 <- GET(URLencode(paste0(host, json$result_url)), add_headers("X-auth-token" = api_token), content_type_json())
      #setTxtProgressBar(pb, 100)  # Set progress to 100% when done
      break
    } else if (res1$status == "error") {
      #close(pb)  # Close progress bar on 
      stop("Error in processing the request.")
    }
    
    Sys.sleep(1)  # Wait before polling again to avoid excessive requests
  }
  
  #close(pb)  # Close progress bar
  
  # Flatten JSON results into a dataframe
  results_json <- jsonlite::fromJSON(content(res2, 'text', encoding = "UTF-8"), simplifyVector = TRUE, flatten = TRUE)
  
  return(results_json)
}

```

## 1 Set list of Annotation set ids to export - GET all c(54,53,62,63,65,173,101,211,343,336) or specify data share groups to filter by

```{r setup_export_grps}

# 594 = Maria KSM308 group 2026


data_share_grps <- c(594) # Set as vector or to NULL if getting all data for api token all = c(54,62, 63,65,173,101,53,211,343,336)
```

```{r list_annot_sets}
#1 Retrieve list of annotation sets from set of data sharing groups=========

annot_set <- tibble() 

for(i_data_share_grps in 1:length(data_share_grps)){
  
  data_share_grp <- data_share_grps[i_data_share_grps]
  url <- paste0(base_url,
                'annotation_set?q={"order_by":[{"field":"created_at","direction":"desc"}],"filters":[{"name":"usergroups","op":"any","val":{"name":"id","op":"in","val":[',
                data_share_grp,
                "]}}]}","&results_per_page=1500")
  json <- get_func(URLencode(url))
  temp <- json$objects %>% as_tibble() %>% select(-c(where(is.list))) %>% 
    mutate(datashare_group_id = data_share_grp) %>%
    subset(annotation_count != 0) %>%
    bind_rows(annot_set)
  annot_set <- temp} 


annot_set  <- distinct(annot_set,id, .keep_all = TRUE) %>% rename(annotation_set_id = id, annotation_set_name = name)
annot_ids <- pull(annot_set, annotation_set_id)
print(length(annot_ids)) # number of annotation sets 
print(sum(annot_set$annotation_count)) # number of annotations
```

```{r deployment_list}
#2 Add list of deployment keys (i.e. Survey_ids)========


deployment_tally <- tibble()

for(i_annot_ids in 1:length(annot_ids)){
  annot_id <- annot_ids[i_annot_ids]
  full_url <- paste0(base_url,
                'annotation/tally/deployment?q={"filters":[{"name":"annotation_set_id","op":"eq","val":',
                annot_id,
                "}]}") 
  results <- run_json_call(
  full_url = full_url,  # The full URL generated by configure_api_call
  api_token = api_token  # The API token loaded by configure_api_call
)
  temp <- results$objects %>% as_tibble() %>% 
    mutate(annotation_set_id = annot_id) %>%
    rename(deployment_id = id,deployment_name = name) %>% 
    bind_rows(deployment_tally)
  deployment_tally <- temp
}

#example urls to test====
#https://squidle.org/api/annotation/tally/deployment?q={%22filters%22:[{%22name%22:%22annotation_set_id%22,%22op%22:%22eq%22,%22val%22:830}]}
#https://squidle.org/api/annotation/tally/deployment?q={"filters":[{"name":"annotation_set_id","op":"eq","val":12477}]}
```

```{r share_grp_info}
#3 Add Datashare group info ==============

url<-paste0(base_url,"groups")

check_pages <- GET(URLencode(url),
                   add_headers("X-Auth-Token"= api_token), content_type_json()) |> 
  content("text", encoding = "UTF-8") |>
  fromJSON(flatten=TRUE)

pgs <- check_pages$total_pages

pages <- c(1:pgs)

datashare_grp <- data.frame()

for(i_pages in 1:length(pages)){
  page <- pages[i_pages]
  
  URL<- glue("{url}?page={page}")
  
  results <- GET(URLencode(URL),
                            add_headers("X-Auth-Token"= api_token), 
                            content_type_json()) |> 
  content("text", encoding = "UTF-8") |> 
  fromJSON(flatten = TRUE) 
  
  results <- as.data.frame(results$objects) |> 
  rename(datashare_group_id = id,datashare_group_name = name) |> 
  select(datashare_group_name,datashare_group_id,groupinfo)
  
  datashare_grp_temp <- bind_rows(datashare_grp,results)
  datashare_grp <- datashare_grp_temp
  
}

##Collate annotation metadata
SQ_RLS_Metadata <- left_join(deployment_tally,annot_set,by = "annotation_set_id") %>%
  mutate(dataset_id= paste(key,label_scheme.id,annotation_set_id,sep="_")) %>% 
  left_join(datashare_grp, by = "datashare_group_id") %>%
  # group_by(dataset_id)  |>
  # dplyr::summarize(datashare_group_id = paste(datashare_group_id, collapse = ",")) |> 
  # ungroup() |> 
  select(key,datashare_group_id,datashare_group_name,label_scheme.name,user.first_name,user.last_name,user.username,
                                      dataset_id,annotation_set_id,annotation_set_name,media_collection.id,media_collection.name,created_at,
                                      is_qaqc,is_final,count,annotation_set_count=annotation_count)

## Find duplicated data ==========================
#i.e. surveys scored more than once in different collections -used to identify unwanted datasets. Get stats on number surveys scored
dups_surveys <- which(duplicated(SQ_RLS_Metadata$key)) # row of duplicated Surveys (2nd and 3rd dup rows after the initial)
dups_surveys <- SQ_RLS_Metadata$key[dups_surveys]## give dup SurvID
length(unique(dups_surveys)) # mum survey_ids duplicated
duplicated_survey_metadata <- SQ_RLS_Metadata %>% group_by(key) %>% 
  filter(n() > 1) %>%
  select(datashare_group_name,count,survey_id=key,label_scheme.name,
         annotation_set_id,annotation_set_count,created_at,annotation_set_name,
         media_collection.id,media_collection.name,user.first_name,user.username,
         datashare_group_id)## Retains all copies of duplicated survey analyses (initial plus 2nd,3rd etc)
#write.csv(duplicated_survey_metadata,glue("data/duplicated-deployment-tally{Sys.Date()}.csv"),row.names = FALSE)
write.csv(SQ_RLS_Metadata,glue("data/Maria-deployment-tally{Sys.Date()}.csv"),row.names = FALSE)
```

```{r, data_export}
#4 Data export=================

include_cols <- paste0(
  c( "label.id",
     "label.name",
     "label.lineage_names",
     "comment",
     "tag_names",
    "needs_review",
    "updated_at",
    "point.id",
    "point.x",
    "point.y",
    "likelihood",
    "point.media.key",
    "point.media.path_best",
    "point.media.deployment.key",
    "label.translated.name",
    "label.translated.translation_info",
    "label.translated.lineage_names",
    "user.username"
     ) %>% 
    paste0('"', ., '"') %>% 
    str_flatten(collapse = ",") %>% 
    paste0("include_columns=[", ., "]")
)

export_data <- tibble()

for(i_annot_ids in 1:length(annot_ids)){
  annot_id <- annot_ids[i_annot_ids]
  full_url <- paste0(base_url,
                "annotation_set/",
                annot_id,"/export?",
                include_cols,
                '&q={"filters":[{"name":"label_id","op":"is_not_null"}]}&translate={"vocab_registry_keys":["worms","caab","catami"],"target_label_scheme_id":2}'# changae back to 58
  )
  
  
  while (TRUE) {
    results <- try(run_json_call(
      full_url = URLencode(full_url),  # The full URL generated by configure_api_call
      api_token = api_token  # The API token loaded by configure_api_call
    ))

    if (inherits(results, "try-error")) {
      Sys.sleep(1)
      # try again
    } else {
      break
      # continue processing results
    }
  }
 
  temp <- results$objects %>% as_tibble() %>% 
    mutate(Annotation_set_id = (results$metadata$id),
           Annotation_set_name= paste(results$metadata$name),
           media_collection_name= paste(results$metadata$media_collection$name),
           tag_name= paste(results$metadata$label_scheme$name),
           labeller_name= paste0(results$metadata$user$first_name,results$metadata$user$last_name),
           dataset_id = paste(results$objects$point.media.deployment.key,results$metadata$label_scheme$name,results$metadata$id,sep = "_")) %>% 
    bind_rows(export_data)
  
  export_data <- temp
}

export_data2 <- export_data |>  select(Annotation_set_id, Annotation_set_name, tag_name, point.media.deployment.key,point.media.key, point.x,point.y,point.id,comment,label.lineage_names,label.name,label.id,label.translated.lineage_names,label.translated.name,label.translated.translation_info
)
write.csv(export_data2,glue("data/Maria_export_data{Sys.Date()}.csv"),row.names = FALSE)
export_data %>% glimpse


##NB This call translates to RLE scheme - which simplifies to relvant RLE indicators (coral, kelp, other) with:  &translate={"vocab_registry_keys":["worms","caab","catami"],"target_label_scheme_id":58}

##example export URL - **use cat() instead of print() or view() to view URLs 


##https://squidle.org/api/annotation_set/874/export?include_columns=[%22label.id%22,%22label.name%22,%22label.lineage_names%22,%22comment%22,%22tag_names%22,%22needs_review%22,%22updated_at%22,%22point.id%22,%22point.x%22,%22point.y%22,%22likelihood%22,%22point.media.key%22,%22point.media.path_best%22,%22point.media.deployment.key%22,%22user.username%22,%22label.translated.name%22,%22label.translated.translation_info%22]&q={"filters":[{"name":"label_id","op":"is_not_null"}]}&translate={"vocab_registry_keys":["worms","caab","catami"],"target_label_scheme_id":58}
```